import type { Categoria } from './Categoria.js';

/**
 * Sugere a categoria de um produto pelo NOME (heurística por palavras-chave).
 * Usado pra classificar em lote os itens que entram como "Outros" (a NFC-e não
 * categoriza) e para auto-categorizar no import. A ordem das regras importa:
 * marcas/sabores (bebida, doce) são checados ANTES de frutas/legumes pra
 * "SUCO ... MORANGO" não virar Fruta. Muitos termos são ABREVIAÇÕES da NFC-e
 * (nomes truncados em ~30 chars): "QJ MUSS", "MOIDA PATIN", "COU FLO", "P O"...
 * Retorna 'Outros' quando não há match confiável.
 */
export function sugerirCategoria(nome: string): Categoria {
  const n = ' ' + String(nome).toUpperCase().replace(/[.,/]/g, ' ') + ' ';
  const h = (re: RegExp): boolean => re.test(n);
  // Leite condensado ("L.COND") antes de Higiene (condicionador) e de Bebidas.
  if (h(/\b(?:L COND|LEITE COND|LEITE MOCA|\bMOCA\b)/)) return 'Laticinios';
  if (
    h(
      /\b(?:COPO|GUARDANAP|GUARD |FILME|PVC|VELA|BALAO|CHUPETA|CHOCALHO|MAMADEIRA|FILTRO PAPEL|INTERFOLHA|POTE|TALHER|GARFO|PALITO|FOSFORO|PILHA|LAMPADA|ARRANJO|PRATO FUND|PRATO RAS|PRATO DESC|PRATO BR|PRATO SOB|PRATOS|CJ )/,
    )
  )
    return 'Utilidades';
  if (
    h(
      /\b(?:REFR|REFRIG|REF\b|SUCO|AGUA|CERVEJA|CAFE|CHA\b|ENERG|RED BULL|NESCAU|ACHOC|TODDY|GATORADE|POWERADE|ISOTON|ISOTO|VINHO|TANG|SUKITA|COCA|GUARANA|FANTA|KUAT|BEB MIST|BEB LAC|WHISKY|VODKA|CACHACA|ESPUMANTE|PROSECCO|CHIMARRAO|ERVA MATE|ESPRESSO|CAPPUCC)/,
    )
  )
    return 'Bebidas';
  if (
    h(
      /\b(?:BISC|BOLACHA|OREO|TRAKINAS|TRIDENT|PASSATEM|NEGRESC|WAFER|COOKIE|BOMBOM|BALA|PIRULITO|CHICL|GOMA|MENTOS|HALLS|TIC TAC|CEREAL|CER MAT|GELATINA|PACOCA|MARSHM|CONF |COBERT|SALG|CHIPS|FOFURA|CHOCOLATE|WILD|LAYS|RUFFLES|DORITOS|CHEETOS|PRINGLES|FANDANGOS|TORCIDA|STIKSY)/,
    ) ||
    h(/\bCHOC(?!ALHO)/)
  )
    return 'Doces';
  if (
    h(
      /\b(?:SABONETE|SAB LIQ|SHAMP|CONDIC|CREME DENT|CR DENT|CRM DENT|PAPEL HIG|P HIG|DESOD|DES\b|ABSORV|ABS\b|FRALD|LENCO|HASTE|COTONE|COTON|ESCOVA DENT|ESC DENT|ANTISSEP|PLAX|GILLET|BARBEAR|AP BARB|VENUS|PRESTO|ALGODAO|DEPIL|ASSADURA|CREME PENT|SEDA|ELSEVE|NIVEA|REXONA|HERBISS|LISTERINE|COLGATE|SORRISO|ORAL B|CLOSE UP|FIO DENT|ENX BUCAL|ENXAG BUCAL|PROT SOLAR|PROTETOR SOLAR|INTIMUS|SEMPRE LIVRE)/,
    )
  )
    return 'Higiene';
  if (
    h(
      /\b(?:DET\b|DETERG|SABAO|SAPON|SAPOL|AMAC|DESINF|SANIT|LIMP|VEJA|LIXO|ESPONJA|BOMBRIL|LA DE ACO|CLORO|LUSTRA|ALVEJ|MULTIUSO|PATO|HARPIC|YPE|VANISH|VANIS|OMO|TIRA MANCHA|PEDRA SANIT|DIFUSOR|INSET|RAID|BLOCO SANIT|FINISH|AJAX|DESENGORD|DESEN\b|TOALHA PAP|PAPEL TOALHA|PAP TOALHA|COMFORT|DOWNY|MON BIJOU|BRILUX)/,
    )
  )
    return 'Limpeza';
  if (
    h(
      /\b(?:LEITE|LTE\b|IOG|QUEIJO|QJO|QJ\b|MUSSAR|MUSS|REQUEIJ|REQ\b|MANTEIG|MARGAR|MARG\b|CREME LEITE|CR LEITE|NATA|DANONE|POLENGH|CATUPIRY|COALHAD|COALHO|GREGO|YAKULT|NESTOG|RICOTA|PROVOLON|PARMES|GORGONZ|CHEDDAR)/,
    )
  )
    return 'Laticinios';
  if (
    h(
      /\b(?:CARNE|FRANGO|LING|LINGUIC|BACON|SALSICH|HOT DOG|PRESUNT|APRESUNT|MORTAD|SALAME|SALAMIT|HAMBURG|PEIXE|SALMAO|TILAPIA|FILE|COSTELA|PICANHA|NUGGET|PIZZA|SEARA|SADIA SAL|MOIDA|PATIN|MUSCULO|MAMINHA|ALCATRA|ACEM|COXAO|FRALDINH|CUPIM|PERNIL|LOMBO|BISTEC|BIST\b|SUINO|BOVIN|FILEZ|MIGNON|PANCETA|PICADINHO|SOBRECOXA)/,
    )
  )
    return 'Carnes';
  if (h(/\b(?:OLEO|AZEITE|GORDURA)/)) return 'Oleos';
  if (
    h(
      /\b(?:MAC\b|MACARR|LASANHA|NHOQUE|MIOJO|LAMEN|TALHARIM|ESPAGUETE|PARAFUSO|TORTELIN|RAVIOLI|CAPELET|PANQUECA)/,
    )
  )
    return 'Massas';
  if (
    h(
      /\b(?:PAO|BISNAG|TORRADA|ROSCA|BOLO|MIST BOL|M BOLO|MISTBOL|COF BOLO|PANETON|CROISS|WRAP|RAP 10|RAP10|PA PAO|PAO QJ|TORTILH|TORTILLA|BAGUET)/,
    )
  )
    return 'Padaria';
  if (
    h(
      /\b(?:ACUCAR|ACUC|ACU |OVOS?\b|SAL\b|FARINHA|FAR\b|FUBA|POLVILHO|AMIDO|MAIZENA|FERM|EXTRATO|MOLHO|TEMPERO|SAZON|CALDO|MAION|KETCHUP|MOSTARDA|VINAGRE|CANELA|OREGANO|COLORIF|COLORAU|SHOYU|FAROFA|PIPOCA|COCO FLOCO|COCO RALADO|PALHA|ALECRIM|ALECRIN|LOURO|CUMINHO|PAPRICA|ACAFRAO|CURRY|TOMILHO|MANJERICAO|TEM MEU SEGRE)/,
    )
  )
    return 'Basicos';
  if (h(/\b(?:MILHO|ERVILHA|SELETA|ATUM|SARDINHA|AZEITON|PALMITO|CONSERV|CHAMPIGNON|PICLES)/))
    return 'Conservas';
  if (
    h(
      /\b(?:BANANA|MACA\b|LARANJA|UVA\b|MAMAO|MELANC|ABACAX|ABACX|MANGA|PERA\b|LIMAO|MORANGO|KIWI|MELAO|ABACATE|AVOCAD|CAQUI|GOIABA|TANGERI|PONKAN|ATEMOYA|FIGO|AMEIXA|PESSEGO|NECTARIN|FRAMBOES|MIRTILO|CEREJA)/,
    )
  )
    return 'Frutas';
  if (
    h(
      /\b(?:TOMATE|CENOURA|BATATA|CEBOLA|ABOBRINHA|ABOBORA|PIMENTAO|BERINJELA|CHUCHU|BETERRABA|MANDIOCA|MANDIOQUINHA|ALHO|VAGEM|QUIABO|PEPINO|ASPARG|EDAMAME|PINHAO|GENGIBRE|INHAME|RABANETE|MIST CHIN)/,
    )
  )
    return 'Legumes';
  if (
    h(
      /\b(?:ALFACE|COUVE|COU FLO|COUV|RUCULA|ESPINAFRE|COENTRO|SALSA|CEBOLINHA|AGRIAO|BROCOLIS|ACELGA|REPOLHO|HORT|ESCAROLA|CHICORIA)/,
    )
  )
    return 'Verduras';
  if (h(/\b(?:ARROZ|FEIJAO|FEIJ|LENTILHA|GRAO DE BICO|QUINOA|CHIA|LINHACA)/)) return 'Graos';
  return 'Outros';
}
